Limpieza de datos

Miguel Angel Argumedo Ortiz

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("bike_buyers.csv")

In [4]:
df.head()

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
0,12591,Married,Female,"30,000",4.0,Graduate Degree,Clerical,Yes,0.0,0-1 Miles,Europe,45.0,No
1,14058,Single,Male,"70,000",0.0,Bachelors,Professional,No,1.0,5-10 Miles,Pacific,41.0,Yes
2,23962,Married,Female,"10,000",0.0,Partial High School,Manual,Yes,2.0,1-2 Miles,Europe,32.0,No
3,23419,Single,Female,"70,000",5.0,Bachelors,Professional,Yes,3.0,10+ Miles,Pacific,39.0,No
4,21940,Married,Male,"90,000",5.0,Graduate Degree,Professional,Yes,0.0,0-1 Miles,North America,47.0,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1251 entries, 0 to 1250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1251 non-null   int64
 1   Marital Status    1244 non-null   object
 2   Gender            1238 non-null   object
 3   Income            1243 non-null   object
 4   Children          1238 non-null   float64
 5   Education         1251 non-null   object
 6   Occupation        1251 non-null   object
 7   Home Owner        1247 non-null   object
 8   Cars              1242 non-null   float64
 9   Commute Distance  1251 non-null   object
 10  Region            1251 non-null   object
 11  Age               1238 non-null   float64
 12  Purchased Bike    1251 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 127.2+ KB

In [6]:
df.describe()

                 ID     Children         Cars          Age
count   1251.000000  1238.000000  1242.000000  1238.000000
mean   20030.208633     1.929725     1.479066    44.058966
std     5331.451777     1.638977     1.121885    11.271138
min    11000.000000     0.000000     0.000000    25.000000
25%    15465.000000     0.000000     1.000000    35.000000
50%    19731.000000     2.000000     1.000000    43.000000
75%    24549.000000     3.000000     2.000000    52.000000
max    29447.000000     5.000000     4.000000    89.000000

In [7]:
df[df.duplicated()]

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
57,20598,Married,Male,"100,000",3.0,Partial High School,Professional,Yes,0.0,10+ Miles,Europe,59.0,Yes
98,19562,Single,Female,"60,000",2.0,Bachelors,Professional,Yes,1.0,2-5 Miles,Pacific,37.0,Yes
116,11270,Married,Male,"130,000",2.0,Graduate Degree,Management,Yes,3.0,0-1 Miles,North America,42.0,Yes
128,20380,Married,Female,"60,000",3.0,Graduate Degree,Management,Yes,2.0,10+ Miles,North America,69.0,No
133,20897,Married,Female,"30,000",1.0,Bachelors,Skilled Manual,Yes,2.0,0-1 Miles,Europe,40.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243,21770,Married,Male,"60,000",4.0,Bachelors,Management,Yes,2.0,10+ Miles,North America,60.0,No
1244,14193,Single,Female,"100,000",3.0,Partial College,Management,Yes,4.0,10+ Miles,Europe,56.0,No
1246,19364,Married,Male,"40,000",1.0,Bachelors,Skilled Manual,Yes,0.0,0-1 Miles,Europe,43.0,Yes
1247,26305,Single,Female,"60,000",2.0,Bachelors,Skilled Manual,No,0.0,0-1 Miles,North America,36.0,Yes
1250,24201,Married,Female,"10,000",2.0,High School,Manual,Yes,0.0,0-1 Miles,Europe,37.0,Yes

In [8]:
df.isna().sum()

ID                   0
Marital Status       7
Gender              13
Income               8
Children            13
Education            0
Occupation           0
Home Owner           4
Cars                 9
Commute Distance     0
Region               0
Age                 13
Purchased Bike       0
dtype: int64

In [17]:
df[df.duplicated(keep=False)].drop_duplicates()

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
1,14058,Single,Male,"70,000",0.0,Bachelors,Professional,No,1.0,5-10 Miles,Pacific,41.0,Yes
2,23962,Married,Female,"10,000",0.0,Partial High School,Manual,Yes,2.0,1-2 Miles,Europe,32.0,No
3,23419,Single,Female,"70,000",5.0,Bachelors,Professional,Yes,3.0,10+ Miles,Pacific,39.0,No
8,18153,Married,Female,"100,000",2.0,Bachelors,Management,Yes,4.0,10+ Miles,Europe,59.0,No
13,11270,Married,Male,"130,000",2.0,Graduate Degree,Management,Yes,3.0,0-1 Miles,North America,42.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,28052,Married,Male,"60,000",2.0,High School,Professional,Yes,2.0,10+ Miles,North America,55.0,No
1099,13415,Single,Male,"100,000",1.0,Graduate Degree,Management,Yes,3.0,2-5 Miles,North America,73.0,Yes
1106,15612,Single,Male,"30,000",0.0,High School,Manual,No,1.0,1-2 Miles,Europe,28.0,No
1136,21260,Single,Female,"40,000",0.0,High School,Skilled Manual,Yes,2.0,5-10 Miles,North America,30.0,No
1177,21770,Married,Male,"60,000",4.0,Bachelors,Management,Yes,2.0,10+ Miles,North America,60.0,No

In [18]:
df["Income"] = pd.to_numeric(df["Income"].str.replace(",",""))

In [20]:
#df = df.drop_duplicates()
df = df.drop_duplicates(subset=["Age"])

In [19]:
columnas = ["Marital Status", "Gender", "Education", "Occupation", "Commute Distance", "Region"]
for col in columnas:
    df[col] = df[col].str.strip().str.replace("Miles","").str.lower()

In [21]:
df = df.dropna(subset=["Age"])

In [22]:
df = df.drop(columns=["Education"])

In [27]:
def far_or_not(x):
  if "+" in str(x):
    return "Far"
  return "Not to far"

In [28]:
df["TYPE"] = df["Commute Distance"].apply(far_or_not)

In [29]:
df.head()

,ID,Marital Status,Gender,Income,Children,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike,TYPE
0,12591,married,female,30000.0,4.0,clerical,Yes,0.0,0-1,europe,45.0,No,Not to far
1,14058,single,male,70000.0,0.0,professional,No,1.0,5-10,pacific,41.0,Yes,Not to far
2,23962,married,female,10000.0,0.0,manual,Yes,2.0,1-2,europe,32.0,No,Not to far
3,23419,single,female,70000.0,5.0,professional,Yes,3.0,10+,pacific,39.0,No,Far
4,21940,married,male,90000.0,5.0,professional,Yes,0.0,0-1,north america,47.0,Yes,Not to far